name: nba
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.5.4 <4.0.0"  # Define the SDK version range

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.0.11
  cached_network_image: ^3.2.0

  # Firebase dependencies
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3  # Update to a compatible version
  cloud_firestore: ^5.5.0
  firebase_database: ^11.1.6
  flutter_tts: ^3.2.0
  provider: ^6.0.0

dev_dependencies:
  flutter_native_splash: ^2.4.2
  flutter_launcher_icons: ^0.14.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_icons:
  android: true  # This will set the icon for Android
  ios: true     # This will set the icon for iOS
  image_path: "assets/images/nbalogo.jpg"  # Path to your app icon image

flutter_native_splash:
  image: assets/images/nbalogo.png
  color: "#ffffff"

flutter:
  uses-material-design: true

  # Assets section:
  assets:
    - assets/images/nbalogo.jpg
  # Optionally, you can add more assets here:
  #   - assets/images/another_image.png
