// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDts6O2SpeK_6uCWQGS2XoJvp2aYe2lEmo',
    appId: '1:788370623158:web:5a890622126cb7a0683417',
    messagingSenderId: '788370623158',
    projectId: 'nbahighlights0603',
    authDomain: 'nbahighlights0603.firebaseapp.com',
    storageBucket: 'nbahighlights0603.firebasestorage.app',
    measurementId: 'G-B5XSL4FKRS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCO39fSiIbNw8ULbzzU0WllUFJQ7kyIEgA',
    appId: '1:788370623158:android:d08654723a811080683417',
    messagingSenderId: '788370623158',
    projectId: 'nbahighlights0603',
    storageBucket: 'nbahighlights0603.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfhfX2GeMaxeuPAXKcYSmK1a6GGI5qm6w',
    appId: '1:788370623158:ios:87527e20229be0d6683417',
    messagingSenderId: '788370623158',
    projectId: 'nbahighlights0603',
    storageBucket: 'nbahighlights0603.firebasestorage.app',
    iosBundleId: 'com.example.nba',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfhfX2GeMaxeuPAXKcYSmK1a6GGI5qm6w',
    appId: '1:788370623158:ios:87527e20229be0d6683417',
    messagingSenderId: '788370623158',
    projectId: 'nbahighlights0603',
    storageBucket: 'nbahighlights0603.firebasestorage.app',
    iosBundleId: 'com.example.nba',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDts6O2SpeK_6uCWQGS2XoJvp2aYe2lEmo',
    appId: '1:788370623158:web:49d5389fae928dc1683417',
    messagingSenderId: '788370623158',
    projectId: 'nbahighlights0603',
    authDomain: 'nbahighlights0603.firebaseapp.com',
    storageBucket: 'nbahighlights0603.firebasestorage.app',
    measurementId: 'G-LHKT0701NH',
  );
}
